version: '2.3'

services:
   sftp:
    build: sftp/ 
    ports:
        - "223:22"
    command: foo:pass:1001
    volumes:
        - /home/mykola/project_devops/python/upload/:/home/foo/upload
    depends_on:
      nginx:
       condition: service_healthy
    healthcheck:
       test: ["CMD", "test", "-e", "/home/mykola/project_devops/nginx/app/"]
       interval: 3s
       timeout: 5s
       retries: 10
       start_period: 1s
   python:
    build: python/
    volumes:
        - /home/mykola/project_devops/python/upload/:/app/
       
   nginx:
    build: nginx/
    ports:
        - "883:80"
    volumes: 
        - /home/mykola/project_devops/nginx/app/:/opt/app/    
    depends_on:
      python:
        condition: service_healthy
    healthcheck:
       test:  ["CMD-SHELL", "test -f /home/mykola/project_devops/python/upload/formatt.xlsx"]
       interval: 3s
       timeout: 5s
       retries: 50
       start_period: 1s    