version: "2.3"
services:
   sftp:
     build: /home/hw12/ftp
     container_name: sftp
     ports:
         - "223:22"
     volumes: 
       - /home/hw12/ftp:/opt/data
       - /home/hw12/ftp:/opt/app
     networks:
       - devops_network
     healthcheck:
       test: ["CMD", "pwd"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

   python:
     build: ./python 
     container_name: python
     volumes: 
       - ./ftp:/opt/data
       - ./ftp:/opt/app
     depends_on:
       redis:
         condition: service_healthy
     environment:
       - ENV=development
     healthcheck:
       test: ["CMD", "python", "sql_orm.py"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

   nginx:
     build: ./nginx
     ports:
       - "80:883"
     volumes:
       - ./ftp:/opt/app
     depends_on:
       redis:
         condition: service_healthy
     environment:
       - ENV=development
     healthcheck:
       test: ["CMD", "ls", "-lsa"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

   redis:
     image: redis
     volumes:
       - ./nginx:/opt/data
     healthcheck:
       test: ["CMD", "ls"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

networks:
  devops_network:
    driver: bridge