version: "2.3"
services:
   sftp:
     build: ./ftp
     container_name: sftp
     ports:
         - "223:22"
     volumes: 
       - ./ftp:/opt/data
       - ./ftp:/opt/app
     networks:
       - devops_network
     healthcheck:
       test: ["CMD", "python", "ps.py"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

   python:
     build: ./python 
     container_name: python
     volumes: 
       - ./python:/opt/data
       - ./python:/opt/app
     depends_on:
       sftp:
         condition: service_healthy
     healthcheck:
       test: ["CMD", "test -f /opt/app/logfile.log"]
       interval: 3s
       timeout: 5s
       retries: 10
       start_period: 1s

   nginx:
     build: ./nginx
     container_name: nginx
     ports:
       - "80:883"
     volumes:
       - ./ftp:/opt/app
     depends_on:
       python:
         condition: service_healthy
     healthcheck:
       test: ["CMD", "ls", "-lsa"]
       interval: 3s
       timeout: 5s
       retries: 5
       start_period: 1s

networks:
  devops_network:
    driver: bridge
