version: "2.3"
services:
   sftp:
     build: /home/testuser/MyProject/lesson
     volumes:
        - /home/testuser/MyProject/lesson/log:/data
     ports:
        - "223:22"
   python:
     build: /home/testuser/MyProject/lesson9
     volumes:
        - /home/testuser/MyProject/lesson9:/data
     healthcheck:
          test: ["CMD", "test", "-e", "/data/access_logs.db" ]
          interval: 3s
          timeout: 5s
          retries: 5
          start_period: 1s
   nginx:
     image: nginx
     ports:
       - "883:80"
     depends_on:
       python:
         condition: service_healthy
     environment:
       - ENV=development




