version: "2.3"
services:
  nginx:
    build: /home/ser/scc/lesson11
    ports:
      - "80:80"
    volumes:
      - /home/ser/scc/lesson11:/data
    depends_on:
      redis:
         condition: service_healthy
    environment:
      - ENV=development
  redis:
    image: redis
    volumes:
      - /home/ser/scc/lesson11:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-v"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
