version: '2.1'

services:
  sshpass:
    build: sshpass/
    volumes:
        - ./logs:/logs
    healthcheck:
       test:  ["CMD-SHELL", "test -f /logs/logfile.log"]
       interval: 30s
       timeout: 30s
       retries: 5
       start_period: 20s
 
  
  sftp:
    build: sftp/
    depends_on:
      sshpass:
        condition: service_healthy
    volumes:
        - ./result:/home/foo/upload
    ports:
        - "223:22"
    command: foo:pass:1001
    
  python:
    build: python/
    depends_on:
      sshpass:
        condition: service_healthy
    volumes:
        - ./logs:/app/logs/
        - ./result:/app/result/
    healthcheck:
       test:  ["CMD-SHELL", "test -f /app/result/access.db"]
       interval: 30s
       timeout: 30s
       retries: 5
       start_period: 20s

  nginx:
    build: nginx/
    ports:
        - "883:80"
    depends_on:
      python:
        condition: service_healthy
    volumes: 
       - ./html:/opt/app/
