# This is a basic workflow to help you get started with Actions
name: valentyn_zakharov_14071979

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - valentyn_zakharov_14071979
  pull_request:
    branches:
      - valentyn_zakharov_14071979

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Setup SSH
      #  run: |
      #    mkdir -p ~/.ssh
      #    echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
      #    chmod 600 ~/.ssh/id_rsa
      #    echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      #  env:
      #    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: path
         run: |
          mkdir /home/testuser/valentyn_zakharov
          cd /home/testuser/valentyn_zakharov
          pwd
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Docker-compose
        run: |
          cd lesson12/my_project
          docker-compose up -d --force-recreate




