name: valentyn_zakharov_14071979

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - valentyn_zakharov_14071979
  pull_request:
    branches:
      - valentyn_zakharov_14071979

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup git repo & docker-compose up 
        run: |
          mkdir -p /home/testuser/valentyn_zakharov_workflow
          cd /home/testuser/valentyn_zakharov_workflow
          git clone https://github.com/pyanush/devops_crash.git || cd /home/testuser/valentyn_zakharov_workflow/devops_crash
          cd /home/testuser/valentyn_zakharov_workflow/devops_crash
          git pull
          git checkout valentyn_zakharov_14071979
          cd lesson12/my_project
          docker-compose up -d --force-recreate
                    
      



